version: "2"
services:
  web:
    build: ./
    command: npm run server
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
volumes:
  ? mongo-volume
